extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:import/recommended
  - plugin:jsx-a11y/recommended
  - prettier

env:
  es2022: true
  browser: true

parserOptions:
  ecmaVersion: latest
  # sourceType: module
  ecmaFeatures:
    jsx: true

settings:
  import/resolver:
    node:
      paths: src
      extensions: [.js, .jsx]
  react:
    version: detect

rules:
  no-console: 1
  quotes: [2, single, { avoidEscape: true }]
  import/order:
    [
      2,
      {
        alphabetize: { order: asc, caseInsensitive: true },
        groups: [builtin, external, internal, [parent, sibling, index]],
        newlines-between: always,
      },
    ]
